#!/bin/sh
#
# Gradle wrapper startup script for StrongholdDroid.
#
# Note: this is a minimal bootstrap. For a real project you'd commit the
# full gradle-wrapper.jar (~60 KB) generated by `gradle wrapper` once.
# This stub assumes gradle-wrapper.jar is present in gradle/wrapper/.
# If missing, it falls back to system gradle as a convenience for dev.

DIR="$(cd "$(dirname "$0")" && pwd)"
WRAPPER_JAR="$DIR/gradle/wrapper/gradle-wrapper.jar"

if [ -f "$WRAPPER_JAR" ]; then
    exec java $JAVA_OPTS -cp "$WRAPPER_JAR" org.gradle.wrapper.GradleWrapperMain "$@"
fi

# Fallback: use system gradle if available
if command -v gradle >/dev/null 2>&1; then
    echo "[strongholddroid] gradle-wrapper.jar missing, falling back to system gradle" >&2
    exec gradle "$@"
fi

echo "[strongholddroid] ERROR: gradle-wrapper.jar missing at $WRAPPER_JAR" >&2
echo "  Run 'gradle wrapper --gradle-version 8.7' once to generate it." >&2
exit 1
